Documentation and Examples Review
g2v-optics/G2VPico pull request #1
Opened 2021-10-27 16:54 UTC by chris-g2v

## Brief
This pull request adds in the initial Python API, documentation, and examples for use with the Pico.

Installation is done using the following command (installs the `dev` branch and instructions will be updated for `main`):
```
pip install git+ssh://git@github.com/g2v-optics/G2VPico.git@dev
```

The _README.md_ file contains basic examples as well as documentation on the different methods available.

The _examples_ directory contains three different example scripts for users to use:
- `example_channel_loop.py` will loop through each channel and increment the value from 0 to the maximum value.  This demonstrates basic control of individual channels, how to loop through the different channels, how to create the instance of `G2VPico` and introduces `channel_limit` which is the maximum value a channel value can be set to.
- `example_spectrum.py` will save the current spectrum into a JSON file.  These spectrum files are not compatible with existing spectrum files generated by the Pico GUI.  The script also takes a pre-existing JSON spectrum file and loads it into the Pico.  This example file demonstrates how to save and load in spectrum files into a Pico and how to create an instance of the `G2VPico` class.
- `example_schedule.py` will load in a test spectrum and then alternate between turning the Pico on or off every 5 seconds.  This example will demonstrate how the user can create their own simple schedule to control their Pico using the `datetime` module.

## To-Do
- Verify that you can install the repo (no need to test whether it works or not)
- Look over documentation in `README.md` file.
- Look over examples to see if anything needs more explanation.

2021-10-28 16:33 UTC, evang2v requested changes
Install fails on my Mac. Please see error:

```
(base) evan@Evans-MacBook-Pro ~ % pip install git+ssh://git@github.com/g2v-optics/G2VPico.git@dev
Collecting git+ssh://****@github.com/g2v-optics/G2VPico.git@dev
  Cloning ssh://****@github.com/g2v-optics/G2VPico.git (to revision dev) to /private/var/folders/7c/mhppfxb17790h4bl5sdmrgq00000gn/T/pip-req-build-ihjc8eyv
  Running command git clone --filter=blob:none -q 'ssh://****@github.com/g2v-optics/G2VPico.git' /private/var/folders/7c/mhppfxb17790h4bl5sdmrgq00000gn/T/pip-req-build-ihjc8eyv
  Warning: Permanently added the RSA host key for IP address '140.82.113.3' to the list of known hosts.
  git@github.com: Permission denied (publickey).
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.
WARNING: Discarding git+ssh://****@github.com/g2v-optics/G2VPico.git@dev. Command errored out with exit status 128: git clone --filter=blob:none -q 'ssh://****@github.com/g2v-optics/G2VPico.git' /private/var/folders/7c/mhppfxb17790h4bl5sdmrgq00000gn/T/pip-req-build-ihjc8eyv Check the logs for full command output.
ERROR: Command errored out with exit status 128: git clone --filter=blob:none -q 'ssh://****@github.com/g2v-optics/G2VPico.git' /private/var/folders/7c/mhppfxb17790h4bl5sdmrgq00000gn/T/pip-req-build-ihjc8eyv Check the logs for full command output.
```

2021-10-28 16:37 UTC, evang2v commented on README.md
> +
I'm not sure if this is just my inexperience with documentation, but I find it hard having arguments and outputs of functions unlabelled as such. Could you label args and returns?

2021-10-28 16:39 UTC, evang2v commented on README.md
> +## Module contents
Is this a phantom section heading? Or does something go here?

2021-10-28 16:40 UTC, evang2v commented on README.md
> +#### set_channel_value(channel, value)
General question: how does the API handle fixed picos? Or do we need to restrict API access to non-fixed picos externally?

2021-10-28 16:43 UTC, evang2v commented on README.md
> +Load in a spectrum either as a json string or a dictionary
In contrast to `set_global_intensity` will this setting take some time? If yes, please add a comment about it.

2021-10-28 16:44 UTC, evang2v commented on README.md
> +Returns the minimum and maximum wavelength values for a channel in nm
What does this mean physically? Is it the range of centre wavelengths that could be on a channel? Or the edges of the Gaussian for the channel's spectrum? Or something else? Clarification needed in the description.

2021-10-28 16:46 UTC, evang2v commented on examples/example_channel_loop.py
> +#!/usr/bin/env python3
Please add a brief description of what this script does, and how it could relate to a customer application. E.g. this script shows how to set the intensity value for each channel, which could be used to load custom spectra to the pico.

2021-10-28 16:46 UTC, evang2v commented on examples/example_channel_loop.py
> +    for channel in pico.channel_list:
I like that this example is agnostic to the channel count of the actual hardware.

2021-10-28 16:47 UTC, evang2v commented on examples/example_schedule.py
> +        print("Setting Pico to use am1.5 spectrum")
Is it AM1.5 or AM1.5g?

2021-10-28 16:49 UTC, evang2v commented on examples/example_schedule.py
> +#!/usr/bin/env python3
Please add a brief description

2021-10-28 16:49 UTC, evang2v commented on examples/example_spectrum.py
> +#!/usr/bin/env python3
Please add a brief description

2021-10-28 16:52 UTC, evang2v commented
@chris-g2v this is looking really good. I've used a bunch of APIs for various scientific instruments, and this one is to the highest standard of cleanliness and usability. Nice.

2021-10-28 17:37 UTC, chris-g2v commented
@evang2v Thank you for the really thorough review.  I think you can't install the package because you are not using a SSH key to connect to the GitHub server but instead using a password.

For password connections you need to use:
```
pip install git+https://git@github.com/g2v-optics/G2VPico.git@dev
```

I will update the documentation to reflect this.

2021-10-28 17:40 UTC, evang2v commented
@chris-g2v Thank you. I get the message: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.

Is it possible to remove authentication entirely, since it's public a repo anyways? Would that be safe? I'd prefer that than having to support each user to set up their GitHub token

2021-10-28 17:49 UTC, chris-g2v commented
@evang2v - It is not a public repo yet.  I am not sure if that would change anything as you still need to be connect to GitHub to fetch the repo which requires authentication.

I would recommend that you set up the token as outlined [here](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/connecting-to-github-with-ssh).

2021-10-28 17:53 UTC, evang2v commented
@chris-g2v I'd prefer to test as a customer would see it. Can you make it public temporarily then private again?

2021-11-17 23:45 UTC, chris-g2v commented on README.md
> +#### set_channel_value(channel, value)
Yes, Fixed Picos support the API (in enabled).  Only the `turn_on()`, `turn_off()` and  `is_fixture_on()` methods are supported for Fixed Picos.

2021-11-17 23:46 UTC, chris-g2v commented on examples/example_schedule.py
> +        print("Setting Pico to use am1.5 spectrum")
Renamed to _test_spectrum.json_ to avoid this confusion.

2021-11-17 23:51 UTC, chris-g2v commented on README.md
> +Returns the minimum and maximum wavelength values for a channel in nm
It should be the edges of the Gaussian for the primary peak of the channel's spectrum.

```
minimum = x0 - 0.5*FWHM
maximum = x0 + 0.5*FWHM
```

2021-11-18 22:41 UTC, evang2v commented
- Install proceeds successfully with `git+https` and no password now. Suggest updating documentation to use `https` instead of `ssh` to avoid users needing to create token.
- Maybe it's a Mac thing, but I can only find folder `g2vpico` after install - no examples, no `Readme.md`. Is that expected behaviour?

2021-11-19 16:08 UTC, chris-g2v commented on README.md
> +Load in a spectrum either as a json string or a dictionary
Added "Channels are changed individually so operation is not instantaneous."

2021-11-19 16:08 UTC, chris-g2v commented
@evang2v I have updated the installation instructions.  As installation will be done via `main`, I have also updated the selected branch.

2021-11-19 16:36 UTC, evang2v commented
@chris-g2v nice.

And what about the install? Are the examples and readme supposed to show up? Or does the setup only copy part of the repo? I can't interpret this from `setup.py`

2021-11-19 16:58 UTC, chris-g2v commented
@evang2v I actually don't think the examples and README are suppose to be installed.  Normally that information is just viewed from the repo directly.  The README and examples can also be downloaded separately.

2021-11-19 17:03 UTC, evang2v commented
@chris-g2v perfect, just wanted to be sure that was expected behaviour. Please add a note at the top of the readme to that effect, so that people aren't searching for examples locally. Then it's good to go!

2021-11-19 17:03 UTC, evang2v approved these changes

2021-11-19 17:13 UTC, merged