Addresses Issue #7: Adds example script to create sawtooth waveform on pico
g2v-optics/G2VPico pull request #8
Opened 2023-05-07 13:10 UTC by miketaschuk

Brief; this pull request adds an 'sawtooth' script to our example set.

2023-05-08 15:04 UTC, chris-g2v requested changes
The pico must also be turned on before starting the waveform loop.

2023-05-08 15:04 UTC, chris-g2v commented on examples/example_sawtooth.py
> +		time_next_action = t0 + timestep		# set time to take next action
You should be using a `timedelta` object to add time to the `datetime.datetime` object instead of `float`. Using the float causes an exception to be called.

2023-05-08 15:14 UTC, miketaschuk commented
Thanks - I'll resolve both of these and resubmit.

2023-05-11 12:48 UTC, miketaschuk commented
@chris-g2v Withdrawing this; got some test reports that give me some additional bugs I should address before adding this.

2023-05-11 12:48 UTC, closed without merging